FROM node:alpine  AS development
ENV NODE_ENV development
ENV PORT 80
WORKDIR /app
COPY ./package*.json /app
RUN npm install
RUN npm install --save-dev json-server
RUN npm install --save-dev concurrently
COPY . .
CMD ["npm", "run", "start-with-mock"]
